cameras_sel: right
cameras_sel_previous: left
features_sel: position
features_sel_previous: speed
individuals_sel: mouse1
keypoints_sel: nose
keypoints_sel_previous: nose
space_sel: x
space_sel_previous: x
trials_sel: 1
audiotrace_visible: true
ephys_visible: true
featureplot_visible: true
labels_visible: true
neo_visible: true
pose_markers_visible: true
spectrogram_visible: true
video_viewer_visible: true
feature_view_mode: Heatmap
