min_label_length_s: 0.05
label_thresholds:
  '3': 0.03
  '8': 0.03
  '9': 0.03
  '10': 0.03
  '17': 0.03
  '24': 0.03
stitch_gap_len_s: 0.015
changepoint_params:
  max_expansion_s: 0.05
  max_shrink_s: 0.05
sr: 200
